// auto-generated by wasmtk hybrid — do not edit manually
// deno-lint-ignore-file

export function toPeriod(u: number, period: number, tol1: number): number {
  console.log('toPeriod begin');
  console.log('u:' + u + ' period:' + period + ' tol1:' + tol1);
  while (u < 0) {
    u += period;
  }
  console.log('u:' + u + ' period:' + period + ' tol1:' + tol1);
  while (u >= period) {
    u -= period;
  }
  console.log('u:' + u + ' period:' + period + ' tol1:' + tol1);
  console.log('Math.abs(u):' + Math.abs(u));

  let d1 = Math.abs(u);
  console.log('d1 = Math.abs(u):' + d1);
  const b1 = d1 <= tol1;
  if (b1) {
    u = 0;
  }

  console.log('u:' + u + ' period:' + period + ' tol1:' + tol1);
  let d2 = u - period;
  console.log('d2:' + d2);
  d2 = Math.abs(d2);
  console.log('Math.abs(d2):' + d2);
  const b2 = d2 <= tol1;
  console.log('b2 = Math.abs(d) <= tol1:' + b2);
  if (b2) {
    u = 0;
  }
  console.log('u:' + u + ' period:' + period + ' tol1:' + tol1);
  console.log('toPeriod end');
  return u
}
