// auto-generated by wasmtk hybrid — do not edit manually
// deno-lint-ignore-file

export function toPeriod(u: number, period: number, tol1: number): number {
  while (u < 0) {
    u += period;
  }
  while (u >= period) {
    u -= period;
  }

  let d1 = abs(u);
  const b1 = d1 <= tol1;
  if (b1) {
    u = 0;
  }

  let d2 = u - period;
  d2 = abs(d2);
  const b2 = d2 <= tol1;
  if (b2) {
    u = 0;
  }
  return u
}

export function toRange(u: number, a: number, b: number, period: number): number {
  while (u < a) {
    u += period;
  }
  while (u > b) {
    u -= period;
  }
  return u
}

export function abs(x: number): number {
  if (x >= 0) {
    return x;
  }
  return -x;
}
